import ReduxProvider from '@/reduxprovider/ReduxProvider'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './style.css'

const aeonikpro = localFont({
  src: [
    {
      path: '../../public/fonts/AeonikPro-Regular.woff2',
      weight: '400',
      style: 'normal'
    },

    {
      path: '../../public/fonts/AeonikPro-Light.woff2',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../../public/fonts/AeonikPro-Bold.woff2',
      weight: '700',
      style: 'normal'
    }
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={aeonikpro.className} suppressHydrationWarning={true}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
